services:
  postgres:
    image: postgres:15.4
    container_name: inhu-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - '5432:5432'
    volumes:
      - inhu-dev-data:/var/lib/postgresql/data
      - ./DB:/docker-entrypoint-initdb.d

volumes:
  inhu-dev-data:
