services:
  postgres:
    image: postgres:15.4
    container_name: inhu-test-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - '5433:5432'
    volumes:
      - inhu-test-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

volumes:
  inhu-test-data:
