global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'dev-monitor'

rule_files:
  - 'config/rule.yml'

scrape_configs:
  - job_name: 'rpi-infra'
    scrape_interval: 10s
    static_configs:
      - targets:
          - 'postgres-exporter:9187'
          - 'redis-exporter:9121'
          - 'node-exporter:9100'
          - 'prometheus:9090'
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*)'
        target_label: instance
        replacement: '$1:rpi'

  - job_name: 'rpi-app'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'api-dev-user.inhu.co.kr:3000'
          - 'api-dev-admin.inhu.co.kr:3001'
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*)'
        target_label: instance
        replacement: '$1:rpi-app'
