name: Build and Deploy Monitoring Stack to EC2 (master)

on:
  push:
    branches:
      - master
    paths:
      - 'scripts/monitoring/**'
    pull_request:
      branches:
        - develop
      paths:
        - 'scripts/monitoring/**'

jobs:
  # Job: 모니터링 스택 배포
  deploy-monitoring:
    # EC2 배포 시 동시 실행 방지
    concurrency:
      group: ec2-deploy
      cancel-in-progress: false
    name: Deploy Monitoring Stack to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 모니터링 번들 패키징
      - name: Package monitoring bundle
        run: tar -czf monitoring.tar.gz -C scripts/monitoring docker-compose.prod.yml grafana prometheus

      # EC2(PROD)로 배포
      - name: Deploy monitoring to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "$KEY" > key.pem
          chmod 400 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST "mkdir -p ~/inhu-monitoring"
          scp -o StrictHostKeyChecking=no -i key.pem monitoring.tar.gz $USER@$HOST:~/inhu-monitoring/
          ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST << 'EOF'
            set -e
            cd ~/inhu-monitoring
            tar -xzf monitoring.tar.gz && rm monitoring.tar.gz
            docker compose -f docker-compose.prod.yml --env-file $HOME/inhu-backend/.env.admin up -d --pull always --remove-orphans --project-name inhu-monitoring-prod
          EOF
