name: Deploy Admin Server

on:
  workflow_call:

jobs:
  # 1. Admin 서버 빌드
  build-admin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Build Admin Server
        run: |
          npx prisma generate
          npm run build admin-server

      - name: Upload Admin artifact
        uses: actions/upload-artifact@v4
        with:
          name: admin-server-build
          path: dist/apps/admin-server

  # 2. Admin 서버 배포
  deploy-admin:
    runs-on: ubuntu-latest
    needs: build-admin
    steps:
      - name: Download Admin artifact
        uses: actions/download-artifact@v4
        with:
          name: admin-server-build
          path: ./deploy-admin-files

      - name: Compress files
        run: tar -czf deploy-admin.tar.gz -C ./deploy-admin-files .

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to Raspberry Pi (reload admin service)
        env:
          HOST: ${{ secrets.RASPBERRY_PI_HOST }}
          USER: ${{ secrets.RASPBERRY_PI_USER }}
          PASSWORD: ${{ secrets.RASPBERRY_PI_PASSWORD }}
          PORT: ${{ secrets.RASPBERRY_PI_PORT }}
        run: |
          sshpass -p "$PASSWORD" scp -P "$PORT" -o StrictHostKeyChecking=no deploy-admin.tar.gz $USER@$HOST:~/inhu-backend/
          sshpass -p "$PASSWORD" ssh -p "$PORT" -o StrictHostKeyChecking=no $USER@$HOST <<'EOF'
            set -e
            cd ~/inhu-backend
            tar -xzf deploy-admin.tar.gz
            rm deploy-admin.tar.gz
            pm2 reload inhu-backend-admin-dev
          EOF
