name: deploy to EC2

on:
  push:
    branches:
      - master
      - develop
      - config

env:
  ENV_FILE: ${{ secrets.ENV_FILE }}

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup-env
    steps:
      - name: Decode and create .env file
        run: echo "$ENV_FILE" | base64 --decode > .env

      - name: Load environment variables globally
        run: cat .env >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.0

      - name: Install dependencies
        run: npm ci

      - name: Start docker services
        run: npm run dev:infra:up

      - name: Test e2e
        run: npm run test:e2e
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          KEY: ${{ secrets.EC2_KEY }}
          USER: ubuntu
        run: |
          echo "$KEY" > key.pem
          chmod 400 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST << 'EOF'
            cd ./inhu-backend
            git reset --hard
            git pull origin develop
            npx pm2 reload inhu-backend          
          EOF
