name: Build and Deploy to Raspberry Pi

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.0

      - name: Install dependencies
        run: npm ci

      - name: Run tests on pull request
        if: github.event_name == 'pull_request'
        run: |
          npm run user-server:test:e2e
          npm run admin-server:test:e2e

      - name: Build for production
        if: github.event_name == 'push'
        run: |
          npx prisma generate
          npm run build user-server
          npm run build admin-server

      - name: Upload build artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: inhu-backend-build
          path: |
            scripts/rdb
            scripts/user-server/dev
            scripts/admin-server/dev
            dist
            prisma
            package.json
            package-lock.json

  deploy:
    name: Deploy to Raspberry Pi
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: inhu-backend-build
          path: ./deploy-files

      - name: Compress deployment files
        run: |
          tar -czf deploy.tar.gz -C ./deploy-files .

      - name: Deploy to Raspberry Pi
        env:
          HOST: ${{ secrets.RASPBERRY_PI_HOST }}
          USER: ${{ secrets.RASPBERRY_PI_USER }}
          PASSWORD: ${{ secrets.RASPBERRY_PI_PASSWORD }}
          PORT: ${{ secrets.RASPBERRY_PI_PORT }}
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          sshpass -p "$PASSWORD" scp -P "$PORT" -o StrictHostKeyChecking=no deploy.tar.gz $USER@$HOST:~/inhu-backend/
          sshpass -p "$PASSWORD" ssh -p "$PORT" -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
          set -e
            cd ~/inhu-backend
            tar -xzf deploy.tar.gz
            rm deploy.tar.gz
            npm ci
            npm run user-server:dev:infra:down
            npm run user-server:dev:infra:up
            npm run admin-server:dev:infra:down
            npm run admin-server:dev:infra:up
            pm2 reload inhu-backend-dev
          EOF
